### ISSUE TITLE
Line Numbers

### ISSUE THREAD

**Issue by ericfowler303** [Qeole/Enlight#1]
I really enjoy having this auto-enabled as it works quite well. Would it be possible to get lined numbers added as an option when viewing a highlighted page?

**Comment by Qeole** [comment]
This sounds like a good idea. Highlight.js has [some support for it](https://github.com/isagalaev/highlight.js/compare/master...line-numbers) but not in the master branch, and has [no plan to merge it](https://highlightjs.readthedocs.org/en/latest/line-numbers.html) for now it seems. But It should not be too hard to reuse their code in the add-on I think.
I'm a bit busy right now but I'll try to give it a shot in a few days/weeks.

**Comment by Qeole** [comment]
@ericfowler303: fixed with commit 531bf3671818c1333f204ec23700e1692393a43e :-).
There's another thing I want to do before submitting again to [AMO](addons.mozilla.org) (namely: switching from cfx to jpm building tool), but you can test the version from this repo meanwhile. I added it as a check-in option, so you have to manually activate line numbers in the add-on prefs.

**Comment by ericfowler303** [comment]
Great stuff! I just tested it out and it works great with the pref. This was done in the currently nightly of course, but I'm sure it will be fine in other versions.

**Comment by Qeole** [comment]
Glad to hear that :-).
I pushed it to AMO tonight, I hope it will be accepted soon and land for all users.
Thanks for feedback!

**Comment by Qeole** [comment]
For your information, it's just been released on addons.mozilla.org (version 1.9.0 of the add-on) if you prefer the “official” reviewed version.
