### ISSUE TITLE
Option to disable syntaxes not needed

### ISSUE THREAD

**Issue by Mikaz-fr** [Qeole/Enlight#13]
It is great that this extension provide support for so many syntaxes. 
But most likely each user don’t deal with such a variety of syntaxes in their daily work. 
Would it be possible to have an option to disable or enable each syntax we want to use with the extension. 

This would hopefully allow to speed up auto detection (not scanning for so many choices) and reduce scrolling time in the available list when the syntax is to be set manually. 

In any case, thanks for the great work.

**Comment by Qeole** [comment]
Hi, I agree with that, it has crossed my mind before.

Hmm so I thought the highlight.js library offered no way to choose what languages to consider for detection, and the only solution would be to embed several versions of the lib. But either my memory failed me or it changed since I last checked the doc. Apparently there _is_ [a way to provide a subset of languages](https://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset).

That's definitely in the TODO list for when I get some time to work on the add-on again :).

Thanks a lot for the feedback!

**Comment by Qeole** [comment]
Now fixed by commit 74fb8ea25103 and previous.

I set the default subset of languages to the default list proposed by the highlight.js lib on their download page, feel free to adapt to your need. Popup gets much cleaner, and autodetection should be a lot faster (and more accurate)!

Pushed to AMO just now, you should get the update anytime in your browser.

**Comment by Mikaz-fr** [comment]
Thanks for the super quick update and new feature.
Indeed the auto-detection is much faster but sadly it broke the drop down menu for me.
I've opened #14
