### ISSUE TITLE
Duet 2 Firmware

### ISSUE THREAD

**Issue by Nachowarrior** [Qeole/Enlight#15]
Does not recognize G-code on duet 2 wifi/ethernet web interface. firmware 2.03.

**Comment by Qeole** [comment]
To be honest, I have no what this refers to. Are you sure this is the project you were looking for?

**Comment by Nachowarrior** [comment]
yes.  duet 2 is a cnc microcontroller. it has a web interface that displays
gcode. your plugin does not highlight any of the code. im trying to use the
firefox addon.

**Comment by Qeole** [comment]
Oh, understood, sorry and thanks for the explanations.

Could you please check and confirm the following:

- Is the code displayed a _non-HTML_ text file? (Just plain text file, with no `<body>`, `<pre>`, or whatever HTML markup could be produced by the web interface?)
- Does the web server use a `Content-Security-Policy:` header in the HTTP reply? Asking because this is a [known reason](https://github.com/Qeole/Enlight/issues/8) why the add-on fails to work on pages from some servers. By the way, is this just auto-highlight that doesn't work, or does manual language selection fail as well?

**Comment by Nachowarrior** [comment]
I am attaching the page source and a screenshot of the code in question
with the add-on enabled.  It is standard http. It does have an option to
secure the page with a password. And yes, i believe it is loading from a .g
or .gcode file. It is not a web page, but is displayed within the web page.
So, I am not really sure how that works. :-D

this is the firmware/software in question:
https://duet3d.dozuki.com/c/DuetWebControl


Hope this helps. I, and I assume many others in the 3d printing community,
would love to have highlighted syntax right in the web control application.
:-D

**Comment by Qeole** [comment]
The [CSP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) is something you get as part as the HTTP reply. On Firefox, I would typically find it with the “developer tools” (network tab - to open before file loads, then in the response headers for the code file).

Thanks for sending the source and screenshots; but I'm sorry, it looks like the attachements didn't make it to the GitHub interface (and I don't see them in email notification either). Would you have a chance to send them again, maybe directly on the GitHub interface, please?

**Comment by Nachowarrior** [comment]
oops. posted it over on your other thread. I didn't cehck before i posted it. Sorry. :-D

**Comment by Qeole** [comment]
No worries. Copying your picture here for the record:

![foo](https://user-images.githubusercontent.com/55152781/64911692-04f3e300-d6f3-11e9-83b5-d58a8fc8e890.PNG)

[Source for the page](https://github.com/Qeole/Enlight/files/3612971/http._192.168.1.9_.zip)

**Comment by Qeole** [comment]
Based on your picture, I'm not sure what we can do. The code is not highlighted because, obviously, the whole page itself is not just a raw text file, it's HTML with a box in which your code is displayed.

We could imagine highlighting the code in the box, but then I see two other issues:

- The G-code displayed in the box is not part of the HTML source, I didn't explore the page in details but I would guess it is loaded from some Javascript code. Which means we would need to have to wait for that code to load in that specific text box before injecting the script for injection. That *might* work, but there's no way that would fit in a generic add-on, that would be very specific to that web interface.

- Furthermore it looks like the box support *editing* the file, not just displaying it. Because syntax highlighting works by adding `<span>` HTML markup with classes related to the different colors to the text, I would be concerned that modifying the text with the add-on may modify the code which is saved in your application when you hit “Save Changes”.

So I don't really see what I could do in your case :/. Did you try to contact the Duet 2 community instead to see if they would have a way to support colors in their interface?

**Comment by Nachowarrior** [comment]
heard.  i appreciate looking into it.

thanks.
